version: "3.8"
networks:
  practica_net:
    driver: bridge
    
services:
  mongodb:
    image: mongo:latest
    env_file: .env
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - 27018:27017
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb_data:/data/db
    networks:
      - practica_net
  backend:
    container_name: backend_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - practica_net
  frontend:
    container_name: frontend_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    command: npm start
    ports:
      - "4000:3000"
    networks:
      - practica_net
  mongo-express:
    container_name: adminMongo_container
    image: mongo-express
    env_file: .env
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - practica_net
  # loadbalancer:
  #   container_name: loadbalancer_container
  #   image: nginx
  #   volumes:
  #     - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #   command: nginx -g daemon off
  #   depends_on:
  #     - backend
  #     - frontend
  #     - mongodb
  #     - mongo-express
  #   networks:
  #    - practica_net
volumes:
  mongodb_data:
